---

- name: ipsec reload
  command: >
    {{strongswan_ipsec_bin}} reload
  when: _strongswan_pkgs is not changed

- name: ipsec secrets reload
  command: >
    {{strongswan_ipsec_bin}} rereadsecrets
  when: _strongswan_pkgs is not changed


# vi:ts=2:sw=2:et:ft=yaml
