---

- name: ipsec reload
  command: >
    {{strongswan_ipsec_bin}} reload
  when: not (_strongswan_pkgs is changed)

- name: ipsec secrets reload
  command: >
    {{strongswan_ipsec_bin}} rereadsecrets
  when: not (_strongswan_pkgs is changed)


# vi:ts=2:sw=2:et:ft=yaml
